### ISSUE TITLE
Problem with connect

### ISSUE THREAD

**Issue by chada** [alienresident/Sketch-Flowchart#1]
Hi, I've installed Sketch Flowchart but it cannot draw lines, other functions are OK.

My Sketch is version 3.4, and I've uninstalled all other plugins in case of hotkey conflict.

Could you help me to detect the problem?

Thanks,

Charles

**Comment by alienresident** [comment]
I haven't updated to 3.4 yet. I'm waiting a few weeks as I have a presentation to do and I don't want and third party plugins that I am demoing to break. 

I usually use the `console` to help with debugging [https://www.sketchapp.com/support/developer/02-common-tasks/03.html](https://www.sketchapp.com/support/developer/02-common-tasks/03.html). [Sketch DevTools](https://github.com/turbobabr/sketch-devtools) was even better but hasn't been maintained.  

It's probably a change to the API. Can you check the `console` log to see if there are any errors after you run the Connect command? We can then check it against the changes in 3.4. Here's a repo of [Sketch Headers](https://github.com/abynim/Sketch-Headers/) with version numbers. 

Hope that helps!

Thanks,
Mark

**Comment by alienresident** [comment]
Fixed by YuriyIlyin PR. Thanks!

**Comment by chada** [comment]
Thanks @YuriyIlyin and @alienresident, that's awesome!
